//! Parity test: Rust gate must match the Python gate paragraph-for-paragraph
//! on a curated fixture.
//!
//! The fixture (`tests/fixtures/parity_inputs.json`) is generated by
//! `tests/gen_parity_fixture.py`, which reconstructs the Python gate inline
//! and computes `expected` for each curated paragraph. Any mismatch between
//! that ground truth and `funding_prefilter::gate_paragraph` is a bug in the
//! Rust prefilter, not in the fixture.

use std::path::PathBuf;

use funding_prefilter::{gate_paragraph, Patterns};

#[derive(serde::Deserialize)]
struct Sample {
    paragraph: String,
    expected: bool,
    category: String,
}

fn load_patterns() -> Patterns {
    let mut yaml_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    yaml_path.push("../../funding_statement_extractor/configs/patterns/funding_patterns.yaml");
    Patterns::load(&yaml_path).expect("load YAML patterns")
}

fn load_fixture() -> Vec<Sample> {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("tests/fixtures/parity_inputs.json");
    let raw = std::fs::read_to_string(&path).expect("read fixture");
    serde_json::from_str(&raw).expect("parse fixture")
}

#[test]
fn rust_gate_matches_python_gate_on_fixture() {
    let patterns = load_patterns();
    let samples = load_fixture();
    assert!(
        samples.len() >= 50,
        "fixture should have at least 50 samples, got {}",
        samples.len()
    );

    let mut mismatches: Vec<(usize, String, bool, bool, String)> = Vec::new();
    for (i, s) in samples.iter().enumerate() {
        let got = gate_paragraph(&s.paragraph, &patterns);
        if got != s.expected {
            mismatches.push((i, s.paragraph.clone(), s.expected, got, s.category.clone()));
        }
    }

    if !mismatches.is_empty() {
        for (i, p, e, g, c) in &mismatches {
            eprintln!("[mismatch #{i} category={c}] expected={e} got={g} paragraph={p:?}");
        }
        panic!(
            "{} parity mismatches between Rust and Python gate",
            mismatches.len()
        );
    }
}
